#! /bin/bash

#solved the problem of "^M"

my_array=(GCGTATTTCTGGTAGCGGCG GGGGCACTAACTATACAGCA GAAACTGGGACTCTTAAGCA GTACAGAGAAAAGGGACAAG GACGTGCCTACGACCCGCCG GCCTCTCTAATGTGGCAGAG GTGAGATGGCCCCTTGAATA GCTACATCTGTCTCTCTGCG GCGGAGGTGTTCAAGCGCCG GGTCAACATGCCAAAGAATG GTCGGGGCCGCCCTCGCTTC GGTGAAGCGGCGGCTCGTGC GCTATCTGCAAAGCACGGTG GTCTCCCTCATCACAGAGCC GGGAGGGTAGCAAGAAGGTA GACCCCGGTGGGCGGCCTTG GTGAGCAAGGACCCAGGCCC GGGCCCACCGTGGCGTATCG GGTTACCAGTGATTGCCCCT GAGGACCCTTAGGTATCTTT)

for i in "${my_array[@]}"
do
  for j in *recom_001.csv
  do 
#    echo "$i"
    k=$(grep -r $i $j)
    l=${k/$j:${i},/}
    l=${l//$'\r'}
#    echo "$k"
    if [ "$l" != "0" ];then 
      echo "$k"
    fi
  done
done